services:
  - name: orders
    root: /home/joe/Code/orders
    log_directories:
      - /home/joe/Code/orders/logs
  - name: payments
    root: /home/joe/Code/payments
    log_directories:
      - /home/joe/Code/payments/logs
